### ISSUE TITLE
yarn installation failure

### ISSUE THREAD

**Issue by michael-lavacca-rw** [openfga/syntax-transformer#156]
### Description

When attempting to install via `yarn` package manager, the installation fails with the following error:

```
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
error Package "" refers to a non-existing file '"/Users/<user>/<parentToRepoDir>/src/language/pkg/js"'.
```

Of note is the path it refers to. It looks like it's missing part of the directory where you would expect it to find a dependency it's looking for. The end of the path would look more accurate like this (for what it's worth): 
 `<parentToRepoDir>/<repoDir>/node_modules/<somePackage>/src/language/pkg/js`

### Reproduction

In a new (or existing) npm initialized repo, install the package with yarn:
- `mkdir testRepo && cd testRepo && npm init -y`
- `yarn add @openfga/syntax-transformer`

### Environment

- **Version of this library used:** 0.1.5
- **Version of the platform or framework used, if applicable:** node 18.18.0 LTS, npm 9.8.1, yarn 1.22.19
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by rhamzeh** [comment]
Thanks for the heads up @michael-lavacca-rw! We'll fix that shortly with `v0.1.6`. Also note that we have an upcoming breaking change you can try out under `v0.2.0-beta.1` that's published from https://github.com/openfga/language/tree/main/pkg/js

This is the README for the upcoming v0.2.0 release: https://github.com/openfga/language?tab=readme-ov-file#transformer

This repo will separate and start publishing frontend related portions under @openfga/frontend-utils

**Comment by rhamzeh** [comment]
@michael-lavacca-rw v0.1.6 should be out now and fixes this issue. Again thank you for reporting it!

**Comment by michael-lavacca-rw** [comment]
That is amazing @rhamzeh ! I can confirm this is working with `0.1.6` now. Thank you and your team so much! 🎉

**Comment by aaguiarz** [comment]
@michael-lavacca-rw out of curiosity, what are you using syntax-transformer for?

Its main use used to be transforming between the JSON <-> DSL format, but you can now do that with the [OpenFGA CLI](url), which we believe is more practical. 

The CLI also lets you [write a file in DSL format directly to the OpenFGA server](https://github.com/openfga/cli#write-authorization-model), instead of going through JSON
