### ISSUE TITLE
Update DSL type restriction for wildcard

### ISSUE THREAD

**Issue by adriantam** [openfga/syntax-transformer#93]
Update type restriction to allow specification on whether wildcard is allowed

**Comment by michelkaeser** [comment]
This is to allow `*` in relation definition which is currently not supported?

**Comment by adriantam** [comment]
> ~This is to allow `*` in relation definition which is currently not supported?~
> 
> Edit: Think I understood the public access documentation wrong. It is not supposed to be in the type definitions.

Currently in v1.0, public access does not restrict/require type to be specified.  However, this will be change in v1.1

It is in relation with https://github.com/openfga/rfcs/blob/0cba9a6f338e39fd53323226192dc0f3981b5fd4/20221012-add-type-restrictions-to-dsl-syntax.md?plain=1#L89 (https://github.com/openfga/rfcs/pull/8)

That is, DSL version 1.1, requires allowed type to be specified.  By default, wildcard are not allowed and it is required that this is to be specified in the allowed type.
